### ISSUE TITLE
Wheels for multiple platforms

### ISSUE THREAD

**Issue by sorami** [WorksApplications/SudachiPy#125]
Travis CI currently fails to deploy to PyPI, as it gives the wheel platform tag `linux_x86_64` which is not accepted by them.

e.g., https://github.com/WorksApplications/SudachiPy/runs/757515277

[Platform compatibility tags — Python Packaging User Guide](https://packaging.python.org/specifications/platform-compatibility-tags/)

We would also want macOS and Windows wheels too. In the end I am thinking of something like dartsclone: https://github.com/rixwew/darts-clone-python/issues/7

**Comment by sorami** [comment]
Maybe [Using Python with GitHub Actions - GitHub Help](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions).

**Comment by polm** [comment]
Ah, sorry about that.

I've built cross-platform wheels in other projects. mecab-python3 uses Travis, fugashi uses Github Actions, and I found Github Actions easier to work with. Maybe the [fugashi actions](https://github.com/polm/fugashi/tree/master/.github/workflows) would be a good reference? Building wheels for Sudachi is probably easier since you don't have to build MeCab first.

**Comment by sorami** [comment]
@polm Thanks for the information! It seems that GitHub Actions is a good option.

**Comment by sorami** [comment]
Currently, able to build wheels for macOS and Windows using Github Actions.

Actions:

- `python-publish.yml`: sdist
- `python-publish-macos.yml`: masos-latest
- `python-publish-windows.yml`: windows-latest, architecture={x64, x86}

For macOS and Windows cases, Python 3.6, 3.7, and 3.8 wheels are created.

[Files on PyPI (v0.4.9)](https://pypi.org/project/SudachiPy/0.4.9/#files)

Linux wheels are not prepared yet.

**Comment by eiennohito** [comment]
0.6.0 provides wheels
